<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_developer_preview</name>
   <tag></tag>
   <elementGuidId>5d4bf6a4-f89f-4d98-8f1b-2c23c2e6e02a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;PolarisRadioButton6]/ancestor::label[@for=&quot;PolarisRadioButton6&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
