<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS04_Register</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7520a160-131e-4332-94e3-2d02fb1741ce</testSuiteGuid>
   <testCaseLink>
      <guid>9dc168b7-6163-49cd-aadc-6a117c0a8c62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopify/TC04_Register_Account</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>230e14ca-81f2-411a-a6cc-31360a0181e7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Register</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4055add1-3cac-4866-be52-008150b8f4b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12cf4e3-f4e9-4752-ab60-e3981fbac542</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a4bd13b-3936-4416-a030-fb73ee42c0d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d59b32d-0f46-4aaf-bc06-8e8d16426dc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c695a060-a7e5-4547-a1c6-9bb74480b5c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>230e14ca-81f2-411a-a6cc-31360a0181e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>069c8652-4d6e-4739-abaa-d4f2653f7962</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
